using ccxt;
namespace Tests;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code


public partial class testMainClass : BaseTest
{
    async static public Task testFetchBorrowRate(Exchange exchange, object code)
    {
        object method = "fetchBorrowRate";
        object borrowRate = null;
        try
        {
            borrowRate = await exchange.fetchBorrowRate(code);
        } catch(Exception ex)
        {
            object message = ((object)ex).ToString();
            // for exchanges, atm, we don't have the correct lists of currencies, which currency is borrowable and which not. So, because of our predetermined list of test-currencies, some of them might not be borrowable, and thus throws exception. However, we shouldn't break tests for that specific exceptions, and skip those occasions.
            if (isTrue(isLessThan(getIndexOf(message, "could not find the borrow rate for currency code"), 0)))
            {
                throw new Exception ((string)message) ;
            }
            // console.log (method + '() : ' + code + ' is not borrowable for this exchange. Skipping the test method.');
            return;
        }
        testBorrowRate(exchange, method, borrowRate, code);
    }

}